const API='https://api.doxomachy.flcrom.dev';
const $=s=>document.querySelector(s);
let bearer=loadAccountToken();
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,3200)}
async function call(path,options={}){const r=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(bearer?{authorization:`Bearer ${bearer}`}:{})}});const d=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw Object.assign(new Error(d.error||'request_failed'),{status:r.status,credits:d.credits});return d}
function showRequest(){$('#requestPanel').hidden=false;$('#sessionPanel').hidden=true}
async function showSession(){try{const d=await call('/v1/auth/session');$('#creditBalance').textContent=d.credits??0;$('#freeShieldBalance').textContent=d.free_shields??0;$('#requestPanel').hidden=true;$('#sessionPanel').hidden=false;loadProfile();showBuy()}catch{clearAccountToken();bearer='';showRequest()}}
$('#linkForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#requestStatus').textContent='';try{await call('/v1/auth/magic-link',{method:'POST',body:JSON.stringify({email:$('#email').value})});$('#requestStatus').textContent='If that address can sign in, a link is on its way. It works once, for 15 minutes.';e.target.reset()}catch(err){if(err.message==='invalid_email')$('#email').setAttribute('aria-invalid','true');$('#requestStatus').textContent=err.message==='invalid_email'?'That email address does not look right.':err.message==='auth_not_configured'?'Sign-in is not configured yet. Try again later.':'Could not request a link. Try again.';button.disabled=false;$('#email').focus()}finally{button.disabled=false}});
$('#email').addEventListener('input',()=>$('#email').removeAttribute('aria-invalid'));
$('#signOut').addEventListener('click',async()=>{try{await call('/v1/auth/session',{method:'DELETE'})}catch{}clearAccountToken();bearer='';showRequest();$('#email').focus();toast('Signed out on this device.')});
let armed=false,forfeit=false;
$('#deleteAccount').addEventListener('click',async()=>{const btn=$('#deleteAccount');if(!armed){armed=true;btn.classList.add('armed');btn.textContent='Click again to permanently delete';$('#sessionStatus').textContent='This removes your sign-in and account. It cannot be undone.';return}btn.disabled=true;try{await call('/v1/auth/account',{method:'DELETE',body:JSON.stringify(forfeit?{forfeit_credits:true}:{})});forfeit=false;clearAccountToken();bearer='';showRequest();$('#email').focus();toast('Account deleted.')}catch(err){if(err.message==='credits_remaining'){forfeit=true;$('#sessionStatus').textContent=`This account still has ${err.credits} unused credit${err.credits===1?'':'s'}. Deleting it gives them up. For a refund, email support first. Click Delete account twice more to delete anyway.`}else $('#sessionStatus').textContent='Could not delete the account. Try again or contact support.'}finally{btn.disabled=false;armed=false;btn.classList.remove('armed');btn.textContent='Delete account'}});
// Buying credits. Stays hidden while paid checkout is off. The buy buttons
// only work after the buyer ticks the withdrawal-waiver consent box, and the
// server refuses a checkout without that consent.
const CHECKOUT_ENABLED=false;
const buyButtons=[...document.querySelectorAll('#buyForm [data-pack]')];
function syncBuy(){const ok=$('#buyConsent').checked;buyButtons.forEach(b=>b.disabled=!ok)}
$('#buyConsent').addEventListener('change',syncBuy);
buyButtons.forEach(b=>b.addEventListener('click',async()=>{if(!$('#buyConsent').checked)return syncBuy();buyButtons.forEach(x=>x.disabled=true);$('#buyStatus').textContent='Opening secure checkout…';const key=Array.from(crypto.getRandomValues(new Uint8Array(18)),x=>x.toString(16).padStart(2,'0')).join('');try{const r=await fetch(API+'/v1/checkout/session',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key,authorization:`Bearer ${bearer}`},body:JSON.stringify({pack:b.dataset.pack,consent:true})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.checkout_url)throw new Error(d.error||'checkout_failed');location.assign(d.checkout_url)}catch(err){$('#buyStatus').textContent=err.message==='pack_unavailable'?'That pack is not available yet.':err.message==='checkout_disabled'?'Buying credits is not open yet.':'Could not open checkout. Try again.';syncBuy()}}));
function showBuy(){$('#buyForm').hidden=!CHECKOUT_ENABLED;syncBuy()}
// Public profile. Name is live; link and image wait for manual review.
let pendingImage;
function showProfile(p){$('#profileName').value=p.name||'';$('#profileLink').value=p.link_pending||p.link||'';$('#linkState').textContent=p.link_pending?'Waiting for review. Not shown yet.':p.link?'Approved and shown on your beliefs.':'';$('#imageState').textContent=p.image_pending?'New image waiting for review. Not shown yet.':p.image?'Approved image shown on your beliefs.':'';$('#clearImage').hidden=!(p.image||p.image_pending)}
async function loadProfile(){try{showProfile(await call('/v1/profile'))}catch{}}
// Resize in the browser so uploads stay small: square crop, 256px JPEG.
function resize(file){return new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const s=Math.min(img.width,img.height),c=document.createElement('canvas');c.width=c.height=256;c.getContext('2d').drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,256,256);URL.revokeObjectURL(url);res(c.toDataURL('image/jpeg',0.82))};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('bad_image'))};img.src=url})}
$('#profileImage').addEventListener('change',async e=>{const f=e.target.files[0];pendingImage=undefined;if(!f)return;try{pendingImage=await resize(f);$('#imageState').textContent='Ready to send for review.'}catch{$('#imageState').textContent='That image could not be read.'}});
$('#clearImage').addEventListener('click',async()=>{try{showProfile(await call('/v1/profile',{method:'PUT',body:JSON.stringify({image:null})}));toast('Image removed.')}catch{toast('Could not remove the image.')}});
const PROFILE_ERRORS={invalid_name:'Names can use letters, numbers and dashes only (up to 24).',invalid_link:'Links must start with https:// and point to a real site.',invalid_image:'That image is too large or not a PNG, JPEG or WebP.',payload_too_large:'That image is too large.'};
$('#profileForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('#profileStatus').textContent='';const body={name:$('#profileName').value.trim()};const link=$('#profileLink').value.trim();body.link=link;if(pendingImage)body.image=pendingImage;try{const p=await call('/v1/profile',{method:'PUT',body:JSON.stringify(body)});pendingImage=undefined;$('#profileImage').value='';showProfile(p);$('#profileStatus').textContent='Saved.'}catch(err){$('#profileStatus').textContent=PROFILE_ERRORS[err.message]||'Could not save. Try again.'}finally{btn.disabled=false}});
if(bearer)showSession();else showRequest();
