const API='https://api.doxomachy.flcrom.dev';
const $=s=>document.querySelector(s);
let bearer=loadAccountToken();
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,3200)}
async function call(path,options={}){const r=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(bearer?{authorization:`Bearer ${bearer}`}:{})}});const d=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw Object.assign(new Error(d.error||'request_failed'),{status:r.status,credits:d.credits});return d}
function showRequest(){$('#requestPanel').hidden=false;$('#sessionPanel').hidden=true}
async function showSession(){try{const d=await call('/v1/auth/session');$('#creditBalance').textContent=d.credits??0;$('#freeShieldBalance').textContent=d.free_shields??0;$('#requestPanel').hidden=true;$('#sessionPanel').hidden=false}catch{clearAccountToken();bearer='';showRequest()}}
$('#linkForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#requestStatus').textContent='';try{await call('/v1/auth/magic-link',{method:'POST',body:JSON.stringify({email:$('#email').value})});$('#requestStatus').textContent='If that address can sign in, a link is on its way. It works once, for 15 minutes.';e.target.reset()}catch(err){if(err.message==='invalid_email')$('#email').setAttribute('aria-invalid','true');$('#requestStatus').textContent=err.message==='invalid_email'?'That email address does not look right.':err.message==='auth_not_configured'?'Sign-in is not configured yet. Try again later.':'Could not request a link. Try again.';button.disabled=false;$('#email').focus()}finally{button.disabled=false}});
$('#email').addEventListener('input',()=>$('#email').removeAttribute('aria-invalid'));
$('#signOut').addEventListener('click',async()=>{try{await call('/v1/auth/session',{method:'DELETE'})}catch{}clearAccountToken();bearer='';showRequest();$('#email').focus();toast('Signed out on this device.')});
let armed=false,forfeit=false;
$('#deleteAccount').addEventListener('click',async()=>{const btn=$('#deleteAccount');if(!armed){armed=true;btn.classList.add('armed');btn.textContent='Click again to permanently delete';$('#sessionStatus').textContent='This removes your sign-in and account. It cannot be undone.';return}btn.disabled=true;try{await call('/v1/auth/account',{method:'DELETE',body:JSON.stringify(forfeit?{forfeit_credits:true}:{})});forfeit=false;clearAccountToken();bearer='';showRequest();$('#email').focus();toast('Account deleted.')}catch(err){if(err.message==='credits_remaining'){forfeit=true;$('#sessionStatus').textContent=`This account still has ${err.credits} unused credit${err.credits===1?'':'s'}. Deleting it gives them up. For a refund, email support first. Click Delete account twice more to delete anyway.`}else $('#sessionStatus').textContent='Could not delete the account. Try again or contact support.'}finally{btn.disabled=false;armed=false;btn.classList.remove('armed');btn.textContent='Delete account'}});
if(bearer)showSession();else showRequest();
