const API='https://doxomachy.matlabdec12.workers.dev';
const $=s=>document.querySelector(s);
let bearer=loadAccountToken();
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,3200)}
async function call(path,options={}){const r=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(bearer?{authorization:`Bearer ${bearer}`}:{})}});const d=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw Object.assign(new Error(d.error||'request_failed'),{status:r.status,credits:d.credits});return d}
function showRequest(){$('#requestPanel').hidden=false;$('#sessionPanel').hidden=true}
async function showSession(){try{const d=await call('/v1/auth/session');$('#creditBalance').textContent=d.credits??0;$('#requestPanel').hidden=true;$('#sessionPanel').hidden=false}catch{clearAccountToken();bearer='';showRequest()}}
$('#linkForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#requestStatus').textContent='';try{await call('/v1/auth/magic-link',{method:'POST',body:JSON.stringify({email:$('#email').value})});$('#requestStatus').textContent='If that address can sign in, a link is on its way. It works once, for 15 minutes.';e.target.reset()}catch(err){$('#requestStatus').textContent=err.message==='invalid_email'?'That email address does not look right.':err.message==='auth_not_configured'?'Sign-in is not configured yet. Try again later.':'Could not request a link. Try again.'}finally{button.disabled=false}});
$('#signOut').addEventListener('click',async()=>{try{await call('/v1/auth/session',{method:'DELETE'})}catch{}clearAccountToken();bearer='';showRequest();toast('Signed out on this device.')});
$('#signOutAll').addEventListener('click',async()=>{try{await call('/v1/auth/sessions',{method:'DELETE'})}catch{}clearAccountToken();bearer='';showRequest();toast('Signed out on all devices.')});
let armed=false;
$('#deleteAccount').addEventListener('click',async()=>{const btn=$('#deleteAccount');if(!armed){armed=true;btn.classList.add('armed');btn.textContent='Click again to permanently delete';$('#sessionStatus').textContent='This removes your sign-in, sessions, and account data. It cannot be undone.';return}btn.disabled=true;try{await call('/v1/auth/account',{method:'DELETE'});clearAccountToken();bearer='';showRequest();toast('Account deleted.')}catch(err){if(err.message==='credits_remaining')$('#sessionStatus').textContent=`This account still has ${err.credits} paid move${err.credits===1?'':'s'}. Contact support for a refund before deleting it.`;else $('#sessionStatus').textContent='Could not delete the account. Try again or contact support.'}finally{btn.disabled=false;armed=false;btn.classList.remove('armed');btn.textContent='Delete account'}});
if(bearer)showSession();else showRequest();
