const API='https://doxomachy.matlabdec12.workers.dev',PUBLIC_SNAPSHOT=globalThis.DOXOMACHY_PUBLIC_SNAPSHOT||'',LIMIT=1000,MAX_SNAPSHOT_AGE=10000;
const SNAPSHOT_CACHE_KEY='doxomachy-public-snapshot';
let sessionToken=sessionStorage.getItem('doxomachy-session')||'';
const $=s=>document.querySelector(s);const clientId=localStorage.getItem('doxomachy-client')||crypto.randomUUID();localStorage.setItem('doxomachy-client',clientId);
let state={memories:[],moves:null,cycle:1,diary:null,version:-1};
let realtime,authorityHealthy=false,readMode='starting',snapshotGeneratedAt=0,statusTimer;
const used=()=>state.memories.reduce((n,m)=>n+m.tokens,0);const ordered=()=>[...state.memories].sort((a,b)=>b.shields-a.shields||a.createdAt-b.createdAt);const weakest=()=>[...state.memories].sort((a,b)=>a.shields-b.shields||a.createdAt-b.createdAt)[0];
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,3200)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function ensureSession(){if(sessionToken)return sessionToken;const r=await fetch(API+'/v1/session',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.error||'session_failed');sessionToken=d.token;sessionStorage.setItem('doxomachy-session',sessionToken);return sessionToken}
async function call(path,options={}){if(options.method==='POST')await ensureSession();const r=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(sessionToken?{authorization:`Bearer ${sessionToken}`}:{ }),...(options.method==='POST'?{'idempotency-key':crypto.randomUUID()}:{ }),...(options.headers||{})}});const data=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw Object.assign(new Error(data.error||'request_failed'),{status:r.status});return data}
function setAuthority(ok){authorityHealthy=ok;document.body.dataset.readMode=ok?'live':'read-only'}
function statusLabel(){if(readMode==='live')return 'Live now';if(!snapshotGeneratedAt)return 'Read-only · freshness unknown';const age=Math.max(0,Date.now()-snapshotGeneratedAt),seconds=Math.floor(age/1000);return `${readMode==='stale'?'Stale':'Read-only'} · ${seconds<60?seconds+'s':Math.floor(seconds/60000)+'m'} old`}
function render(changed){const list=$('#memoryList'),items=ordered(),locked=!authorityHealthy;list.innerHTML=items.length?items.map((m,i)=>`<li class="memory-item ${m.id===changed?'changed':''}" data-id="${m.id}"><span class="rank">${String(i+1).padStart(2,'0')}</span><div><p class="belief-text">${escapeHtml(m.text)}</p><p class="meta">${escapeHtml(m.alias||'anonymous')} · ${m.tokens} tokens</p></div><div class="actions"><button class="shield-button" data-protect="${m.id}" type="button" ${locked?'disabled':''}>Protect</button><span class="shield-count">${m.shields} ${m.shields===1?'shield':'shields'}</span></div></li>`).join(''):'<li class="empty">No beliefs yet. The first sentence will define the mind.</li>';const count=used(),pct=Math.min(100,Math.round(count/LIMIT*100));$('#capacityPercent').textContent=`${pct}%`;$('#meterFill').style.width=`${pct}%`;$('.meter').setAttribute('aria-valuenow',pct);$('#tokenCount').textContent=`${count} / ${LIMIT.toLocaleString()} tokens`;$('#movesLeft').textContent=state.moves===null?'—':state.moves;$('#openComposer').disabled=locked;$('#beliefForm').querySelector('button[type="submit"]').disabled=locked;$('#weakest').textContent=weakest()?`#${String(items.findIndex(m=>m.id===weakest().id)+1).padStart(2,'0')}`:'—';const d=state.diary?new Date(state.diary.created_at):new Date();$('#diaryDate').textContent=d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});$('#diaryText').textContent=state.diary?.text||'The first generated diary will appear after the next midnight cycle.';$('#diarySources').textContent=state.diary?'Generated from the surviving public memory':'No diary generated yet';$('#updatedAt').textContent=statusLabel();list.querySelectorAll('[data-protect]').forEach(b=>b.addEventListener('click',()=>protect(b.dataset.protect)))}
function validSnapshot(d,requireFreshness=false){return requireFreshness?DoxomachySnapshotState.valid(d):!!d&&Number.isSafeInteger(d.version)&&d.version>=0&&Array.isArray(d.beliefs)&&Number.isFinite(d.cycle)}
function cachedSnapshot(){try{const d=JSON.parse(localStorage.getItem(SNAPSHOT_CACHE_KEY)||'null');return validSnapshot(d,true)?d:null}catch{return null}}
function rememberSnapshot(d){if(DoxomachySnapshotState.shouldPersist(d,state.version))try{localStorage.setItem(SNAPSHOT_CACHE_KEY,JSON.stringify(d))}catch{}}
async function fetchSnapshot(){if(!PUBLIC_SNAPSHOT){const d=await call(`/v1/mind?clientId=${encodeURIComponent(clientId)}`);d.generatedAt=Date.now();d._authoritative=true;return d}const r=await fetch(PUBLIC_SNAPSHOT,{headers:{accept:'application/json'}});const d=await r.json().catch(()=>null);if(!r.ok||!validSnapshot(d,true))throw new Error('snapshot_unavailable');return d}
function applyPublic(d,source){snapshotGeneratedAt=Number(d.generatedAt)||Date.now();const authoritative=source==='realtime'||source==='mutation'||d._authoritative===true;setAuthority(authoritative);readMode=authoritative?'live':Date.now()-snapshotGeneratedAt>MAX_SNAPSHOT_AGE?'stale':'read-only';if(!authoritative)state.moves=null;state.memories=d.beliefs||[];state.cycle=d.cycle||1;state.diary=d.diary||null;state.version=d.version;if(d.moves!==undefined)state.moves=d.moves;rememberSnapshot(d);render()}
async function refreshMoves(){if(!sessionToken)return;try{const d=await call(`/v1/mind?clientId=${encodeURIComponent(clientId)}`);if(d.moves!==undefined){state.moves=d.moves;render()}}catch{}}
async function load(){const cached=cachedSnapshot();if(cached)realtime.apply(cached,'cache');try{realtime.apply(await fetchSnapshot(),'initial')}catch{setAuthority(false);readMode=cached?(Date.now()-cached.generatedAt>MAX_SNAPSHOT_AGE?'stale':'read-only'):'unavailable';render();toast(cached?'Showing saved memory. Moves are locked until live service returns.':'Live memory is unavailable. Moves are locked.')}}
async function protect(id){if(!authorityHealthy)return toast('Moves are locked until live service returns.');if(state.moves!==null&&state.moves<=0)return toast('No free moves remain. Paid moves are not active.');try{const d=await call(`/v1/beliefs/${id}/protect`,{method:'POST',body:JSON.stringify({clientId})});realtime.apply({...d.mind,diary:state.diary},'mutation');state.moves=d.moves;render(id);toast('Belief protected.')}catch(e){toast(e.message==='no_moves'?'No free moves remain.':'Could not protect that belief.')}}
$('#openComposer').addEventListener('click',()=>{if(!authorityHealthy)return toast('Moves are locked until live service returns.');$('#composer').hidden=false;$('#beliefText').focus();$('#composer').scrollIntoView({behavior:'smooth',block:'start'})});$('#closeComposer').addEventListener('click',()=>{$('#composer').hidden=true});
$('#beliefText').addEventListener('input',e=>{$('#charCount').textContent=`${e.target.value.length} / 120`;$('#evictionPreview').textContent='Final token count and any eviction are calculated by the server.'});
$('#beliefForm').addEventListener('submit',async e=>{e.preventDefault();if(!authorityHealthy)return toast('Moves are locked until live service returns.');if(state.moves!==null&&state.moves<=0)return toast('No free moves remain.');const button=e.submitter;button.disabled=true;button.textContent='Adding…';try{const d=await call('/v1/beliefs',{method:'POST',body:JSON.stringify({text:$('#beliefText').value,alias:$('#alias').value,clientId})});realtime.apply({...d.mind,diary:state.diary},'mutation');state.moves=d.moves;e.target.reset();$('#charCount').textContent='0 / 120';$('#evictionPreview').textContent='';$('#composer').hidden=true;render(d.belief.id);toast(d.evicted.length?`Added. ${d.evicted.length} weak belief disappeared.`:'Belief added to the public mind.')}catch(err){toast(err.message==='invalid_belief'?'That belief was rejected by the safety rules.':err.message==='no_moves'?'No free moves remain.':'Could not add the belief. Try again.')}finally{button.disabled=false;button.textContent='Use one free move'}});
$('#shareDiary').addEventListener('click',async()=>{const text=`Doxomachy diary\n\n${$('#diaryText').textContent}\n\nhttps://doxomachy.vercel.app/`;try{await navigator.clipboard.writeText(text);toast('Diary copied.')}catch{toast('Copy failed. Select the diary text instead.')}});
realtime=DoxomachyRealtime.create({url:API.replace(/^http/,'ws')+'/v1/realtime',fetchSnapshot,onSnapshot:applyPublic,onStatus:s=>{if(s==='connected')refreshMoves();if(s==='reconnecting'){setAuthority(false);readMode=snapshotGeneratedAt&&Date.now()-snapshotGeneratedAt>MAX_SNAPSHOT_AGE?'stale':'read-only';render()}}});
realtime.start();load();statusTimer=setInterval(()=>{if(!authorityHealthy&&snapshotGeneratedAt){readMode=Date.now()-snapshotGeneratedAt>MAX_SNAPSHOT_AGE?'stale':'read-only';$('#updatedAt').textContent=statusLabel()}},1000);
addEventListener('pagehide',()=>{clearInterval(statusTimer);realtime.stop()},{once:true});
