import {describe,it,expect,vi} from 'vitest';
import {makePublicSnapshot,publishIfNewer,snapshotLag} from '../src/public-snapshot';
const r2=(version=-1,delay=0)=>{let stored=version;const puts:number[]=[];return {puts,bucket:{head:vi.fn(async()=>stored<0?null:{customMetadata:{version:String(stored)}}),put:vi.fn(async(_k:string,_b:string,o:any)=>{if(delay)await new Promise(r=>setTimeout(r,delay));stored=Number(o.customMetadata.version);puts.push(stored)})} as any,get version(){return stored}}};
describe('public snapshot',()=>{
 it('contains no private state and requires generatedAt',()=>{const s=makePublicSnapshot({version:7,beliefs:[{id:'b'}],cycle:3,diary:{text:'x'},sessions:{secret:1} as never},1234);expect(s).toEqual({type:'snapshot',version:7,beliefs:[{id:'b'}],cycle:3,diary:{text:'x'},generatedAt:1234});expect(JSON.stringify(s)).not.toContain('secret')});
 it('publishes with the approved cache policy',async()=>{const x=r2();expect(await publishIfNewer({PUBLIC_SNAPSHOT:x.bucket},makePublicSnapshot({version:2,beliefs:[],cycle:1},55))).toBe('published');const [,body,o]=x.bucket.put.mock.calls[0];expect(JSON.parse(body)).toMatchObject({version:2,generatedAt:55});expect(o.httpMetadata.cacheControl).toBe('public, s-maxage=2, stale-while-revalidate=30, stale-if-error=86400')});
 it('rejects seed and repair downgrades',async()=>{const x=r2(8);expect(await publishIfNewer({PUBLIC_SNAPSHOT:x.bucket},makePublicSnapshot({version:7,beliefs:[],cycle:1}))).toBe('current');expect(x.puts).toEqual([])});
 it('serial execution preserves version order even when a put is slow',async()=>{const x=r2(-1,25);await publishIfNewer({PUBLIC_SNAPSHOT:x.bucket},makePublicSnapshot({version:3,beliefs:[],cycle:1}));await publishIfNewer({PUBLIC_SNAPSHOT:x.bucket},makePublicSnapshot({version:4,beliefs:[],cycle:1}));expect(x.puts).toEqual([3,4]);expect(x.version).toBe(4)});
 it('reports lag and fails closed without blocking authority',async()=>{const x=r2(2);expect(await snapshotLag({PUBLIC_SNAPSHOT:x.bucket},5)).toEqual({enabled:true,publishedVersion:2,lag:3});x.bucket.put.mockRejectedValueOnce(new Error('down'));x.bucket.head.mockResolvedValueOnce(null);expect(await publishIfNewer({PUBLIC_SNAPSHOT:x.bucket},makePublicSnapshot({version:6,beliefs:[],cycle:1}))).toBe('failed');expect(await publishIfNewer({},makePublicSnapshot({beliefs:[],cycle:1}))).toBe('disabled')});
});
